# -*- coding: utf-8 -*-
"""CobaMF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nimj19XC1VqyMF0XuXSz0uNOuyL_xq3F
"""

print(20*"=")
print("MATCH FACTOR")
print(20*"=")

JumlahHD = float(input("Masukkan Jumlah HD: "))
Serving = float(input("Masukkan Waktu Serving: "))
CTHD = float(input("Masukkan CTHD: "))

hasil = (JumlahHD * Serving) / CTHD
print(f"Hasilnya adalah {hasil}")

if hasil >= 1:
    print(f"HD pasti Ngantri")
else:
    print(f"PC gantung ya")